### ISSUE TITLE
Very low light level readings

### ISSUE THREAD

**Issue by jalbarra** [D-Winker/TSL2591_AutoAdjust#2]
Hi,
I need to get small variations in very low light levels to monitor human access in caves. I have configured the TSL2591 with maximum gain and integration time, a persistence of 40 and thresholds between 0 and 5, but sometimes I get erratic readings. Any advice to avoid them and maintain maximum sensitivity?
Thanks !

**Comment by D-Winker** [comment]
The first thing that comes to mind is the dark count - the datasheet specifies it as 0 to 20. Are your measurements small enough that this would have an impact? 

About the "persistence of 40 and the thresholds between 0 and 5" - I'm not familiar with the term persistence in the context of this sensor, and what is the threshold on? Are you looking at thresholded data, as opposed to the raw values?

**Comment by jalbarra** [comment]
I have consulted the datasheet and, indeed, the dark count option appears, but with an integration time of 100 ms and maximum gain, in this case the count is between 0 and 20. But it seems that the maximum sensitivity is obtained with gain maximum and integration time of 600 ms, so I do not quite understand this option. I'll do some tests to see the results
Regarding the use of persistence and threshold data, these are used so that the sensor can sleep and activate an interruption only in the event that the reading is within the upper and lower limits, and after the number of readings exceeds the persistence figure
In my case, I have a setting to activate an interrupt (and wake the microcontroller) after 40 above 0 and below 5. I understand that the persistence data is used to avoid false readings due to noise

**Comment by D-Winker** [comment]
I should clarify - dark count is not an option, it is noise that has various causes - for example, part of the dark count is thermal noise. The datasheet specifies that for integration time of 100 ms and maximum gain, the dark count is between 0 and 20. This means the sensor can always report values between 0 and 20, even if there is no light.
For an integration time of 600 ms, I expect the dark count to fall between 0 and 120 (6 times larger). The values you are looking for are very small, and the dark noise looks likely to be causing your problems.

It might be possible to characterize the noise by covering the sensor completely and taking measurements. With a better understanding of it, you may be able to better determine real and fake events. For example - the dark counts might have random time and magnitude, and the real events might have consistent magnitude for a period of time.

Another possibility is to use two sensors and see if the data is correlated. I would expect a real light source to cause similar measurements in multiple sensors, while the dark counts should not correlate well.

**Comment by jalbarra** [comment]
Thanks for the clarification about the dark count, I had indeed misinterpreted your previous comment
I will take your advice into account, I need to do more tests to decide the best solution to avoid or minimize false readings
Best regards,

**Comment by D-Winker** [comment]
Best of luck. Closing because this issue seems to be inherent to the sensor, as opposed to this code.
